events {}

http {
    server {
        listen 80;

        #
        # Tarball Requests von Firely
        #
        # Zuerst ganz normal an Verdaccio:
        #
        #   /de.gematik.ti/-/de.gematik.ti-1.4.1-draft.1.tgz
        #
        # Falls Verdaccio 404 liefert, wird @fhir_tarball_fallback
        # aufgerufen.
        #
        location ~ \.tgz$ {
            proxy_pass http://verdaccio:4873;

            proxy_set_header Host $http_host;
            proxy_set_header X-Forwarded-Host $http_host;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-Port 4873;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

            proxy_intercept_errors on;
            error_page 404 = @fhir_tarball_fallback;
        }

        #
        # Firely/Simplifier Compatibility Fallback
        #
        # Firely:
        #
        #   /de.fhir.medication/-/de.fhir.medication-1.0.4.tgz
        #
        # wird zu:
        #
        #   /de.fhir.medication/-/1.0.4
        #
        location @fhir_tarball_fallback {
            rewrite ^/([^/]+)/-/[^/]+-(.+)\.tgz$ /$1/-/$2 break;

            proxy_pass http://verdaccio:4873;

            proxy_set_header Host $http_host;
            proxy_set_header X-Forwarded-Host $http_host;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-Port 4873;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        #
        # Alle anderen Requests normal an Verdaccio
        #
        location / {
            proxy_pass http://verdaccio:4873;

            proxy_set_header Host $http_host;
            proxy_set_header X-Forwarded-Host $http_host;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-Port 4873;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}